### ISSUE TITLE
LWP::Parallel::UserAgent

### ISSUE THREAD

**Issue by nigelhorne** [kjetilk/p5-lwp-useragent-chicaching#1]
This is a question rather than a bug, is this module compatible with LWP::Parallel::UserAgent, and if so would you please document an example?

**Comment by kjetilk** [comment]
I'm sorry, but I really can't tell. It is possible, given that I only hook into LWP::UserAgent by wrapping around the request method. However, from some comments in the code and the changelog, it appears LWP::Parallel::UserAgent does not support HTTP/1.1, which happened in LWP::UserAgent a really long time ago, so it seems that LWP::Parallel::UserAgent reimplements much more than I would find comfortable to work with... 

All this would have been much easier to work with if LWP adopted a Moo::Role based architecture in such a way that you could compose your UA...

Anyway, you could just try and see?
