### ISSUE TITLE
 LWP::UserAgent::Cache::CHI

### ISSUE THREAD

**Issue by nigelhorne** [kjetilk/p5-lwp-useragent-chicaching#2]
Wouldn't it be better to call it LWP::UserAgent::Cache::CHI to be in-line with the already existing module LWP::UserAgent::Cache::Memcached?

**Comment by kjetilk** [comment]
I considered it, but, the thing is that you could well use memcached as a cache backend for CHI, and so the analogy isn't a good one, I felt that it might just confuse people into thinking CHI is sort of a replacement for memcached, which it isn't, it is a framework that can use e.g. memcached. I don't really think the name is very important, but there are pros and cons to every choice, but I didn't think LWP::UserAgent::Cache::CHI was a very good choice... :-)

Kjetil

**Comment by kjetilk** [comment]
It is going into Debian now, so I guess the name has just stuck... :-)
